package framework.wsclient.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2017-06-02T15:08:50.862+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://service.pacp.faf.com", name = "BankNoInquiry")
@XmlSeeAlso({ObjectFactory.class})
public interface BankNoInquiry {

    @WebResult(name = "bankNoInquiryReturn", targetNamespace = "http://service.pacp.faf.com")
    @RequestWrapper(localName = "bankNoInquiryRequest", targetNamespace = "http://service.pacp.faf.com", className = "com.yqjr.modules.dto.BankNoInquiryRequest")
    @WebMethod
    @ResponseWrapper(localName = "bankNoInquiryResponse", targetNamespace = "http://service.pacp.faf.com", className = "com.yqjr.modules.dto.BankNoInquiryResponse")
    public BankNoInquiryResponseReurn bankNoInquiryRequest(
        @WebParam(name = "header", targetNamespace = "http://service.pacp.faf.com")
        PacpHeader header,
        @WebParam(name = "body", targetNamespace = "http://service.pacp.faf.com")
        BankNoInquiryRequestDTO body
    );
}
