
package framework.wsclient.dto;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0 2017-06-02T15:08:50.830+08:00
 * Generated source version: 3.0.0
 * 
 */
public final class BankNoInquiry_BankNoInquiry_Client {

	private static final QName SERVICE_NAME = new QName("http://service.pacp.faf.com", "BankNoInquiryService");

	private BankNoInquiry_BankNoInquiry_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = BankNoInquiryService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		BankNoInquiryService ss = new BankNoInquiryService(wsdlURL, SERVICE_NAME);
		BankNoInquiry port = ss.getBankNoInquiry();

		{
			System.out.println("Invoking bankNoInquiryRequest...");
			PacpHeader _bankNoInquiryRequest_header = null;
			BankNoInquiryRequestDTO _bankNoInquiryRequest_body = null;
			BankNoInquiryResponseReurn _bankNoInquiryRequest__return = port
					.bankNoInquiryRequest(_bankNoInquiryRequest_header, _bankNoInquiryRequest_body);
			System.out.println("bankNoInquiryRequest.result=" + _bankNoInquiryRequest__return);

		}

		System.exit(0);
	}

}
