package com.yqjr.modules.job.entity;

import com.yqjr.framework.base.BaseEntity;
import com.yqjr.framework.datatype.Date;
import com.yqjr.modules.job.entity.Job;

public class Job extends BaseEntity<Long, Job> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4814840992409006639L;

	private String frequency;//执行频率    一次/每天/每周/每月
	private String exectime;//执行时间
	private String execWeeks;//每周时，选择星期
	private String execDays;//每月时，选择日期
	
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private Date jobNextExectime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private Integer jobStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobCron;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECSTATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private Integer jobExecStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobExecResult;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobExecNode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private Long jobExecCost;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobClass;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.ID
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.ID
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.ID
	 *
	 * @param id
	 *            the value for ESB.PAY_SYS_JOBDEF.ID
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @param jobName
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public Date getJobNextExectime() {
		return jobNextExectime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @param jobNextExectime
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobNextExectime(Date jobNextExectime) {
		this.jobNextExectime = jobNextExectime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public Integer getJobStatus() {
		return jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @param jobStatus
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobStatus(Integer jobStatus) {
		this.jobStatus = jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobCron() {
		return jobCron;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @param jobCron
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobCron(String jobCron) {
		this.jobCron = jobCron;
	}

	/**
	 * @return the jobExecStatus
	 */
	public Integer getJobExecStatus() {
		return jobExecStatus;
	}

	/**
	 * @param jobExecStatus
	 *            the jobExecStatus to set
	 */
	public void setJobExecStatus(Integer jobExecStatus) {
		this.jobExecStatus = jobExecStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobExecResult() {
		return jobExecResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @param jobExecResult
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobExecResult(String jobExecResult) {
		this.jobExecResult = jobExecResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobExecNode() {
		return jobExecNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @param jobExecNode
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobExecNode(String jobExecNode) {
		this.jobExecNode = jobExecNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public Long getJobExecCost() {
		return jobExecCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @param jobExecCost
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobExecCost(Long jobExecCost) {
		this.jobExecCost = jobExecCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobClass() {
		return jobClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @param jobClass
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobClass(String jobClass) {
		this.jobClass = jobClass;
	}

	/**
	 * @return the frequency
	 */
	public String getFrequency() {
		return frequency;
	}

	/**
	 * @param frequency the frequency to set
	 */
	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	/**
	 * @return the exectime
	 */
	public String getExectime() {
		return exectime;
	}

	/**
	 * @param exectime the exectime to set
	 */
	public void setExectime(String exectime) {
		this.exectime = exectime;
	}

	/**
	 * @return the execWeeks
	 */
	public String getExecWeeks() {
		return execWeeks;
	}

	/**
	 * @param execWeeks the execWeeks to set
	 */
	public void setExecWeeks(String execWeeks) {
		this.execWeeks = execWeeks;
	}

	/**
	 * @return the execDays
	 */
	public String getExecDays() {
		return execDays;
	}

	/**
	 * @param execDays the execDays to set
	 */
	public void setExecDays(String execDays) {
		this.execDays = execDays;
	}
	
}