package com.yqjr.modules.job.condition;

import com.yqjr.framework.base.BaseCondition;
import com.yqjr.framework.datatype.Date;

public class JobCondition extends BaseCondition<JobCondition> {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private Date jobNextExectime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobCron;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECSTATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobExecStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobExecResult;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobExecNode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private Long jobExecCost;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	private String jobClass;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @param jobName
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_NAME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public Date getJobNextExectime() {
		return jobNextExectime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @param jobNextExectime
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_NEXTEXECTIME
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobNextExectime(Date jobNextExectime) {
		this.jobNextExectime = jobNextExectime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobStatus() {
		return jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @param jobStatus
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_STATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobCron() {
		return jobCron;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @param jobCron
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_CRON
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobCron(String jobCron) {
		this.jobCron = jobCron;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECSTATUS
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_EXECSTATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobExecStatus() {
		return jobExecStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECSTATUS
	 *
	 * @param jobExecStatus
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_EXECSTATUS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobExecStatus(String jobExecStatus) {
		this.jobExecStatus = jobExecStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobExecResult() {
		return jobExecResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @param jobExecResult
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_EXECRESULT
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobExecResult(String jobExecResult) {
		this.jobExecResult = jobExecResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobExecNode() {
		return jobExecNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @param jobExecNode
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_EXECNODE
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobExecNode(String jobExecNode) {
		this.jobExecNode = jobExecNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public Long getJobExecCost() {
		return jobExecCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @param jobExecCost
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_EXECCOST
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobExecCost(Long jobExecCost) {
		this.jobExecCost = jobExecCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @return the value of ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public String getJobClass() {
		return jobClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @param jobClass
	 *            the value for ESB.PAY_SYS_JOBDEF.JOB_CLASS
	 *
	 * @mbg.generated Tue May 16 17:13:46 CST 2017
	 */
	public void setJobClass(String jobClass) {
		this.jobClass = jobClass;
	}
}