package com.yqjr.modules.serverlog.entity;

import com.yqjr.framework.base.BaseEntity;
import com.yqjr.framework.datatype.Date;
import com.yqjr.modules.serverlog.entity.ServerLog;

public class ServerLog extends BaseEntity<String, ServerLog> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4469329124173881284L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.SERIALNO
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String serialNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.CHANNEL
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String channel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.SERVICECODE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String serviceCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.TRANSACTIONTIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private Date transactionTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.TOKEN
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String token;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.REQUESTTIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private Date requestTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.RESPONSETIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private Date responseTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.RESPONSETOKEN
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String responseToken;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.REPLYCODE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String replyCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.REPLYTEXT
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String replyText;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.SENDMESSAGE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String sendMessage;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_SERVERLOG.RECEIVEMESSAGE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	private String receiveMessage;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.SERIALNO
	 *
	 * @return the value of ESB.FMK_SERVERLOG.SERIALNO
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getSerialNo() {
		return serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.SERIALNO
	 *
	 * @param serialNo
	 *            the value for ESB.FMK_SERVERLOG.SERIALNO
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.CHANNEL
	 *
	 * @return the value of ESB.FMK_SERVERLOG.CHANNEL
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.CHANNEL
	 *
	 * @param channel
	 *            the value for ESB.FMK_SERVERLOG.CHANNEL
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.SERVICECODE
	 *
	 * @return the value of ESB.FMK_SERVERLOG.SERVICECODE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getServiceCode() {
		return serviceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.SERVICECODE
	 *
	 * @param serviceCode
	 *            the value for ESB.FMK_SERVERLOG.SERVICECODE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.TRANSACTIONTIME
	 *
	 * @return the value of ESB.FMK_SERVERLOG.TRANSACTIONTIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public Date getTransactionTime() {
		return transactionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.TRANSACTIONTIME
	 *
	 * @param transactionTime
	 *            the value for ESB.FMK_SERVERLOG.TRANSACTIONTIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.TOKEN
	 *
	 * @return the value of ESB.FMK_SERVERLOG.TOKEN
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.TOKEN
	 *
	 * @param token
	 *            the value for ESB.FMK_SERVERLOG.TOKEN
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.REQUESTTIME
	 *
	 * @return the value of ESB.FMK_SERVERLOG.REQUESTTIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public Date getRequestTime() {
		return requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.REQUESTTIME
	 *
	 * @param requestTime
	 *            the value for ESB.FMK_SERVERLOG.REQUESTTIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.RESPONSETIME
	 *
	 * @return the value of ESB.FMK_SERVERLOG.RESPONSETIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public Date getResponseTime() {
		return responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.RESPONSETIME
	 *
	 * @param responseTime
	 *            the value for ESB.FMK_SERVERLOG.RESPONSETIME
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.RESPONSETOKEN
	 *
	 * @return the value of ESB.FMK_SERVERLOG.RESPONSETOKEN
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getResponseToken() {
		return responseToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.RESPONSETOKEN
	 *
	 * @param responseToken
	 *            the value for ESB.FMK_SERVERLOG.RESPONSETOKEN
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setResponseToken(String responseToken) {
		this.responseToken = responseToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.REPLYCODE
	 *
	 * @return the value of ESB.FMK_SERVERLOG.REPLYCODE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getReplyCode() {
		return replyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.REPLYCODE
	 *
	 * @param replyCode
	 *            the value for ESB.FMK_SERVERLOG.REPLYCODE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setReplyCode(String replyCode) {
		this.replyCode = replyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.REPLYTEXT
	 *
	 * @return the value of ESB.FMK_SERVERLOG.REPLYTEXT
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getReplyText() {
		return replyText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.REPLYTEXT
	 *
	 * @param replyText
	 *            the value for ESB.FMK_SERVERLOG.REPLYTEXT
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setReplyText(String replyText) {
		this.replyText = replyText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.SENDMESSAGE
	 *
	 * @return the value of ESB.FMK_SERVERLOG.SENDMESSAGE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getSendMessage() {
		return sendMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.SENDMESSAGE
	 *
	 * @param sendMessage
	 *            the value for ESB.FMK_SERVERLOG.SENDMESSAGE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setSendMessage(String sendMessage) {
		this.sendMessage = sendMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_SERVERLOG.RECEIVEMESSAGE
	 *
	 * @return the value of ESB.FMK_SERVERLOG.RECEIVEMESSAGE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public String getReceiveMessage() {
		return receiveMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_SERVERLOG.RECEIVEMESSAGE
	 *
	 * @param receiveMessage
	 *            the value for ESB.FMK_SERVERLOG.RECEIVEMESSAGE
	 *
	 * @mbg.generated Thu Jun 15 15:20:15 CST 2017
	 */
	public void setReceiveMessage(String receiveMessage) {
		this.receiveMessage = receiveMessage;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.yqjr.framework.base.BaseEntity#getId()
	 */
	@Override
	public String getId() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.yqjr.framework.base.BaseEntity#setId(java.lang.Object)
	 */
	@Override
	public void setId(String id) {
		// TODO Auto-generated method stub
		
	}
	
	
}