package com.yqjr.modules.clientlog.condition;

import com.yqjr.framework.base.BaseCondition;
import com.yqjr.framework.datatype.Date;

public class ClientLogCondition extends BaseCondition<ClientLogCondition> {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.MSGREFNO
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private String msgRefNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.CHANNEL
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private String channel;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.SERVICECODE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private String serviceCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.EXTERNALREFERENCENO
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private String externalReferenceNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.TRANSACTIONDATE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private Date transactionDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.REQUESTTIME
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private Date requestTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.RESPONSETIME
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private Date responseTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.REPLYCODE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private String replyCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_CLIENTLOG.REPLYTEXT
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	private String replyText;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.MSGREFNO
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.MSGREFNO
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public String getMsgRefNo() {
		return msgRefNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.MSGREFNO
	 *
	 * @param msgRefNo
	 *            the value for ESB.FMK_CLIENTLOG.MSGREFNO
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setMsgRefNo(String msgRefNo) {
		this.msgRefNo = msgRefNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.CHANNEL
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.CHANNEL
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.CHANNEL
	 *
	 * @param channel
	 *            the value for ESB.FMK_CLIENTLOG.CHANNEL
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.SERVICECODE
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.SERVICECODE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public String getServiceCode() {
		return serviceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.SERVICECODE
	 *
	 * @param serviceCode
	 *            the value for ESB.FMK_CLIENTLOG.SERVICECODE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.EXTERNALREFERENCENO
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.EXTERNALREFERENCENO
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public String getExternalReferenceNo() {
		return externalReferenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.EXTERNALREFERENCENO
	 *
	 * @param externalReferenceNo
	 *            the value for ESB.FMK_CLIENTLOG.EXTERNALREFERENCENO
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setExternalReferenceNo(String externalReferenceNo) {
		this.externalReferenceNo = externalReferenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.TRANSACTIONDATE
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.TRANSACTIONDATE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public Date getTransactionDate() {
		return transactionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.TRANSACTIONDATE
	 *
	 * @param transactionDate
	 *            the value for ESB.FMK_CLIENTLOG.TRANSACTIONDATE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.REQUESTTIME
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.REQUESTTIME
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public Date getRequestTime() {
		return requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.REQUESTTIME
	 *
	 * @param requestTime
	 *            the value for ESB.FMK_CLIENTLOG.REQUESTTIME
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.RESPONSETIME
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.RESPONSETIME
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public Date getResponseTime() {
		return responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.RESPONSETIME
	 *
	 * @param responseTime
	 *            the value for ESB.FMK_CLIENTLOG.RESPONSETIME
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.REPLYCODE
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.REPLYCODE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public String getReplyCode() {
		return replyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.REPLYCODE
	 *
	 * @param replyCode
	 *            the value for ESB.FMK_CLIENTLOG.REPLYCODE
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setReplyCode(String replyCode) {
		this.replyCode = replyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_CLIENTLOG.REPLYTEXT
	 *
	 * @return the value of ESB.FMK_CLIENTLOG.REPLYTEXT
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public String getReplyText() {
		return replyText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_CLIENTLOG.REPLYTEXT
	 *
	 * @param replyText
	 *            the value for ESB.FMK_CLIENTLOG.REPLYTEXT
	 *
	 * @mbg.generated Wed Jun 07 09:10:53 CST 2017
	 */
	public void setReplyText(String replyText) {
		this.replyText = replyText;
	}
}