package com.yqjr.modules.menu.model;

import com.yqjr.framework.base.BaseModel;
import com.yqjr.modules.menu.entity.Menu;

public class MenuModel extends BaseModel<Integer, MenuModel> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1578728805632505722L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.PARENT_ID
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private String parentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.PARENT_IDS
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private String parentIds;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.NAME
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.SORT
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private Integer sort;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.URL
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private String url;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.ICON
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private String icon;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.IS_SHOW
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private String isShow;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ESB.FMK_MENU.PERMISSION
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	private String permission;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.PARENT_ID
	 *
	 * @return the value of ESB.FMK_MENU.PARENT_ID
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.PARENT_ID
	 *
	 * @param parentId
	 *            the value for ESB.FMK_MENU.PARENT_ID
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.PARENT_IDS
	 *
	 * @return the value of ESB.FMK_MENU.PARENT_IDS
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public String getParentIds() {
		return parentIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.PARENT_IDS
	 *
	 * @param parentIds
	 *            the value for ESB.FMK_MENU.PARENT_IDS
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.NAME
	 *
	 * @return the value of ESB.FMK_MENU.NAME
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.NAME
	 *
	 * @param name
	 *            the value for ESB.FMK_MENU.NAME
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.SORT
	 *
	 * @return the value of ESB.FMK_MENU.SORT
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.SORT
	 *
	 * @param sort
	 *            the value for ESB.FMK_MENU.SORT
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.URL
	 *
	 * @return the value of ESB.FMK_MENU.URL
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.URL
	 *
	 * @param url
	 *            the value for ESB.FMK_MENU.URL
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.ICON
	 *
	 * @return the value of ESB.FMK_MENU.ICON
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.ICON
	 *
	 * @param icon
	 *            the value for ESB.FMK_MENU.ICON
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.IS_SHOW
	 *
	 * @return the value of ESB.FMK_MENU.IS_SHOW
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public String getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.IS_SHOW
	 *
	 * @param isShow
	 *            the value for ESB.FMK_MENU.IS_SHOW
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ESB.FMK_MENU.PERMISSION
	 *
	 * @return the value of ESB.FMK_MENU.PERMISSION
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ESB.FMK_MENU.PERMISSION
	 *
	 * @param permission
	 *            the value for ESB.FMK_MENU.PERMISSION
	 *
	 * @mbg.generated Tue Jun 06 09:58:35 CST 2017
	 */
	public void setPermission(String permission) {
		this.permission = permission;
	}

	private Menu parent;

	public Menu getParent() {
		return parent;
	}

	public void setParent(Menu parent) {
		this.parent = parent;
	}

	/* (non-Javadoc)
	 * @see com.yqjr.framework.base.BaseModel#getTransactionalKey()
	 */
	@Override
	public String getTransactionalKey() {
		// TODO Auto-generated method stub
		return null;
	}
}